<?php

function boosted_node_validate($node, $form, &$form_state) {
  if ($node->type != 'artist_page') {
    return; // only need to act on artist nodes
  }
  if ($node->nid !== NULL) {
    return;
  }
  module_load_include('inc', 'pathauto'); // needed to load library functions from pathauto
  if (drupal_lookup_path('source', pathauto_cleanstring($node->title))) {
    form_set_error('title', t('Title already taken. Titles are considered the same if they would get the same URL. E.g. "Title Page" = "tITle-PaGe"'));
  }
}

function boosted_civi_path() {
  return realpath(dirname(__FILE__).'/../../contrib/civicrm');
}

function boosted_node_submit($node, $form, &$form_state) {
  if ($node->type != 'artist_page') {
    return;
  }
  
  return;
  civicrm_initialize();
  $results = civicrm_api("Campaign","create", array ('version' =>'3', 'name' =>'TestCampaign', 'title' =>'Test Campaign', 'description' =>'MY DESC', 'start_date' =>'2012-07-01', 'end_date' =>'2012-09-01', 'goal_revenue' =>'2000', 'goal_general' =>'10000'));
  print_r($results);
  die();
}

function boosted_form_user_register_form_alter(&$form, &$form_state) {
  drupal_add_js(drupal_get_path('module', 'boosted') .'/user-registration.js');
  $form['#validate'][] = 'boosted_user_register_form_validate';
}

function boosted_user_register_form_validate($node, &$form) {
  $bank_account_no = $form['input']['custom_10'];
  if (!preg_match('/^[0-9]{2}[ -]?[0-9]{4}[ -]?[0-9]{7}[ -]?[0-9]{2,3}$/', $bank_account_no)) {
      form_set_error('user_register', t('Please enter a valid New Zealand bank account number (e.g. 01 1234 1234567 12).'));
      return;
  }
  return;
}
